### Juno Network

[[chain]]
id = "juno-1"
key_format = { type = "bech32", account_key_prefix = "junopub", consensus_key_prefix = "junovalconspub" }
state_file = "$KMS_HOME/state/juno-1-consensus.json"